name: Build and Push Docker Image

on:
  # 可以在推送到主分支时触发
  push:
    branches: [ main ]
  # 可以手动触发
  workflow_dispatch:
  # 可以设置定时触发
  # schedule:
  #   - cron: '0 0 * * *'  # 每天 UTC 时间 0 点运行

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone Qwen2API repository
        run: |
          git clone https://github.com/Rfym21/Qwen2API.git
          cd Qwen2API
          ls -la  # 列出文件，确认克隆成功

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/Qwen2API
          tags: |
            type=raw,value=latest
            type=sha,format=short
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Qwen2API
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
